'p: animations':
  - packages/animations/**/*

'p: cross_file':
  - packages/cross_file/**/*

'p: css_colors':
  - packages/css_colors/**/*

'p: dynamic_layouts':
  - packages/dynamic_layouts/**/*

'p: extension_google_sign_in_as_googleapis_auth':
  - packages/extension_google_sign_in_as_googleapis_auth/**/*

'p: flutter_adaptive_scaffold':
  - packages/flutter_adaptive_scaffold/**/*

'p: flutter_image':
  - packages/flutter_image/**/*

'p: flutter_lints':
  - packages/flutter_lints/**/*

'p: flutter_markdown':
  - packages/flutter_markdown/**/*

'p: flutter_migrate':
  - packages/flutter_migrate/**/*

'p: flutter_template_images':
  - packages/flutter_template_images/**/*

'p: go_router':
  - packages/go_router/**/*

'p: go_router_builder':
  - packages/go_router_builder/**/*

'p: imitation_game':
  - packages/imitation_game/**/*

'p: metrics_center':
  - packages/metrics_center/**/*

'p: multicast_dns':
  - packages/multicast_dns/**/*

'p: palette_generator':
  - packages/palette_generator/**/*

'p: pigeon':
  - packages/pigeon/**/*

'p: pointer_interceptor':
  - packages/pointer_interceptor/**/*

'p: rfw':
  - packages/rfw/**/*

'p: standard_message_codec':
  - packages/standard_message_codec/**/*

'p: web_benchmarks':
  - packages/web_benchmarks/**/*

'p: xdg_directories':
  - packages/xdg_directories/**/*

'p: cupertino_icons':
  - third_party/packages/cupertino_icons/**/*
