name: flutter_migrate
description: A tool to migrate legacy flutter projects to modern versions.
version: 0.0.1
repository: https://github.com/flutter/packages/tree/main/packages/flutter_migrate
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3Ap%3A%20flutter_migrate
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  args: ^2.3.1

dev_dependencies:
