name: imitation_game
description: Testing framework for comparing multiple frameworks' performance.
repository: https://github.com/flutter/packages/tree/main/packages/imitation_game
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+imitation_game%22
version: 0.0.2+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.3.1
  mustache_template: ^2.0.0
